### ISSUE TITLE
KEEP SCORE!!!!!!!!!

### ISSUE THREAD

**Issue by Panzarotti** [Panzarotti/EleeStuff#7]
HOW MANY RECTANGLES DID U TaaaaaaaaaaaAPPPPPPPPPPPP!!!!!!!!!!!!!!!!!

**Comment by kuhrusty** [comment]
Arghh!!

Also, you wanted the final score to include some assessment, like "amazing" or "wow, you are really terrible at this."  (Maybe that's a separate issue, though.)

**Comment by Panzarotti** [comment]
You suck
You tried?

**Comment by Panzarotti** [comment]
Next, pop up a different Activity showing score, high score, retry button, final speed.

**Comment by kuhrusty** [comment]
A note from tonight's commit message:

We're not displaying the score when the game ends because a good tile reached the bottom of the screen.  The bit which displays the score at the end of the game should be moved into a new method, and that method should be called when the person hits a bad tile (where we're currently calling `Toast.makeText()`), and also when we decide the game is over because a good tile hit the bottom of the screen.

**Comment by kuhrusty** [comment]
> Next, pop up a different Activity showing score, high score, retry button, final speed.

Regarding having a separate Activity which displays scores and starts the game: having one Activity launch another is done with `startActivity()`; there's an example of this in our `MainActivity.onOptionsItemSelected()`.  That gets called when someone selects one of the menu items like "Tiles, I guess?" or "Slappy Balls" or whatever.

Inside that `onOptionsItemSelected()` method, there are some comments on launching child Activities.  It mentions `startActivityForResult()`, which is what you call if you want information *back* from the new Activity.  We **do** want information back: we want to know their score, etc.  When you call `startActivityForResult()`, and the child Activity (which will be our `TileActivity`, which runs the game) completes (which is what will happen when the game is over), the child Activity can send some information (their score, etc.) back to the parent Activity.  

So, the things we want to do:
1. Create some new Activity which will be our start screen: it'll display a title, high scores, etc.  It will also have a "start" button or something.  We can create this new Activity through Android Studio's File -> New -> Activity -> ... which will let us choose the kind of Activity to add.
1. Put a "start" button or something in the new Activity.
1. Add a method on our new Activity, something like `startGame()` (we can call it whatever we want), and configure that start button to call `startGame()` when it's clicked.
1. Inside `startGame()`, call `startActivityForResult()`, passing an `Intent` (that's an Android thing) which refers to our `TileActivity`, so that a new instance of our `TileActivity` class gets launched when `startGame()` is called.
1. Also in our new Activity, add an `onActivityResult()` method which is going to get called when our `TileActivity` finishes.  (More on that below.)
1. Fiddle with our `MainActivity.onOptionsItemSelected()` so that, when the "Tiles, I guess?" menu item is selected, we launch our new Activity instead of `TileActivity`.
1. Finally, in our TileActivity, we need to *exit the activity* when the game ends.  *When we do that,* we need to pass back the information our parent Activity (the new one we created above) wants (our score, etc.).  To do that, we're going to call `setResult()` and `finish()`.  *When* we call `setResult()`, we're going to pass a new `Intent` containing the information we want to send back.  We will add a new method which does this, and we'll call that method when the user taps a bad tile, and when a good tile reaches the bottom of the screen.
1. Oh yeah, back in our new game-starting-Activity's `onActivityResult()`, we probably want to check to see whether the new score is a high score, and update our saved high scores if necessary.

Regarding that `onActivityResult()` method, it's going to look like this:

    @Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {

The `Intent` is going to be the one we created in our TileActivity when we decided the game was over.

**Comment by kuhrusty** [comment]
> Finally, in our TileActivity, we need to *exit the activity* when the game ends.

*Or,* we could launch a *new* Activity which is responsible for displaying the score, the "Wow, you... tried?" feedback, asking for their initials, etc.  We would launch that in `TileActivity` using `startActivityForResult()`, and when our `TileActivity.onActivityResult()` was called (indicating that the new show-their-score Activity had called `finish()`), *we* would call `finish()` too, bailing back to the original start-the-game Activity.

Although that might *sound* more complicated (three Activity classes instead of two), it might actually be simpler: instead of having an Activity which has to display their score & feedback *if* they just finished a game (and do something else if they haven't started a game yet), we would have one start-game activity which always just displays the high scores and the start-game button, and another end-game activity which always just displays the score, the feedback, and maybe shows a field for entering their initials.

(That is, having two simple Activities with clear jobs to do is probably a lot easier to understand & debug than one complicated Activity which has to do different things depending on whether the user has just finished a game.)

**Comment by kuhrusty** [comment]
We've done all that stuff above, but this can't really be closed until they look better.  Right now they've got horrible temporary layouts.

**Comment by kuhrusty** [comment]
The layouts aren't perfect, but they're less horrible; closing.
