### ISSUE TITLE
Stop registering clicks when there's a bad tile

### ISSUE THREAD

**Issue by Panzarotti** [Panzarotti/EleeStuff#9]

**Comment by kuhrusty** [comment]
Right now, when we have a bad tile (and before the "start" tile is clicked), we're setting speed to 0, which causes cells to not move when `update()` gets called.  However, `update()` is still being called 30 times per second by our `SceneUpdateThread` which is created in `TileActivity`.  Seems like, instead of setting speed to 0, we should start & stop the thread which calls `update()`.

**Comment by kuhrusty** [comment]
I think we fixed this by launching GameOverActivity when we hit a bad tile (issue #7).
